package com.paxcel.mail.controller;

import java.io.IOException;

import javax.mail.MessagingException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.paxcel.mail.components.AutoTemplateGenerator;
import com.paxcel.mail.components.HtmlGenerateServiceInterface;
import com.paxcel.mail.domain.Mail;
import com.paxcel.mail.model.ModelMain;
import com.paxcel.mail.service.EmailServiceHtmlGeneration;

@RestController
public class NewJsonRestController {
	
	 private static Logger log = LoggerFactory.getLogger(NewJsonRestController.class);
	 
	 private static String HTML_CONTENT=null;
	 
	 @Autowired
	 private HtmlGenerateServiceInterface htmlGenerateServiceInterface;
	 
	 @Autowired
	 private EmailServiceHtmlGeneration emailServiceHtmlGeneration;
	 
	// @Autowired private AutoTemplateGenerator autoTemplateGenerator;
	 
	 @PostMapping(value="/newJsonRequest", headers="Accept=application/json",produces = MediaType.APPLICATION_JSON_VALUE)
	  public ResponseEntity<ModelMain> sendByJson(@RequestBody ModelMain mainModel) {
		 log.info("Before Object Get ");
		 System.out.println("Main-Model Header "+mainModel.getPageName());
		 

		 log.info("After Object Get ");
		 return new ResponseEntity<ModelMain>(mainModel,HttpStatus.OK);
	 }
	 
     @GetMapping("/newJsonRequest")
     public ResponseEntity<ModelMain> emailTemplate( Model model) {
    	   log.info("Before Object Get ");
	   Resource resource = new ClassPathResource("/static/newjson.json");
	   ModelMain modelMain = null;
	   try {
            ObjectMapper mapper = new ObjectMapper();
            modelMain = mapper.readValue(resource.getInputStream(), ModelMain.class);
            HTML_CONTENT = htmlGenerateServiceInterface.createHtmlTags(modelMain).toString();
           
            Mail mail = new Mail(); 
			  mail.setFrom("yourmail@gmail.com");
			
              mail.setTo("friendsmail@outlook.com");
			  mail.setSubject("Demo Header Of a Dummy Mail");
			  try {
				emailServiceHtmlGeneration.sendGeneratedMail(mail,HTML_CONTENT);
				//  emailServiceHtmlGeneration.sendGeneratedMail(mail,autoTemplateGenerator.getAutoGeneratedTemplate());
			  } catch (MessagingException e) {
				  log.error(e.getMessage());
		          return new ResponseEntity<ModelMain>(modelMain,HttpStatus.BAD_GATEWAY);
			  }
            
        } catch (IOException e) {
           log.error(e.getMessage());
           return new ResponseEntity<ModelMain>(modelMain,HttpStatus.NOT_FOUND);
        }
	       log.info("After Object Get ");
        return new ResponseEntity<ModelMain>(modelMain,HttpStatus.OK);
    }

}
